#ifndef CARD_H
#define CARD_H

enum class Card {
	CLUB_ACE, CLUB_2, CLUB_3, CLUB_4, CLUB_5, CLUB_6, CLUB_7, CLUB_8, CLUB_9, CLUB_10, CLUB_JACK, CLUB_QUEEN, CLUB_KING,
	DIAMOND_ACE, DIAMOND_2, DIAMOND_3, DIAMOND_4, DIAMOND_5, DIAMOND_6, DIAMOND_7, DIAMOND_8, DIAMOND_9, DIAMOND_10, DIAMOND_JACK, DIAMOND_QUEEN, DIAMOND_KING,
	HART_ACE, HART_2, HART_3, HART_4, HART_5, HART_6, HART_7, HART_8, HART_9, HART_10, HART_JACK, HART_QUEEN, HART_KING,
	SPADE_ACE, SPADE_2, SPADE3, SPADE_4, SPADE_5, SPADE_6, SPADE_7, SPADE_8, SPADE_9, SPADE_10, SPADE_JACK, SPADE_QUEEN, SPADE_KING,
	NO_VALUE
};

#endif // CARD_H
